swagger: '2.0'
basePath: /api/3/datasets
consumes:
  - applicaiton/json
produces:
  - applicaiton/json
info:
  version: 3.0.0
  title: Datasets
parameters:
  fulllistParam:
    name: full-list
    in: query
    description: Enables or disables the return ov objects rather then uuids
    required: false
    allowEmptyValue: false
    type: boolean
    format: boolean
  fulllistfieldsParam:
    name: full-list-fields
    in: query
    description: Fields to be returnd when full-list is enabled
    required: false
    format: string
    type: array
    items:
      type: string
    collectionFormat: csv
definitions:
  uuid:
    type: string
    pattern: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
  dataset:
    properties:
      metadata:
        type: object
      description:
        type: string
      image_size:
        type: integer
      imported:
        type: integer
      name:
        type: string
      networks:
        type: array
        items:
          $ref: '#/definitions/uuid'
      os:
        type: string
      requirements:
        type: array
        items:
          $ref: '#/definitions/dataset_reqs'
      status:
        type: string
      type:
        type: string
      version:
        type: string
      uuid:
        $ref: '#/definitions/uuid'
  dataset_reqs:
    properties:
      attribute:
        type: string
      condition:
        type: string
      value:
        type: string
      weight:
        type: string
paths:
  #------------------
  # Datasets
  #------------------
  '/':
    get:
      tags:
        - 'datasets'
      summary: Lists all Datasets visible to the user
      description: |
        See Get Dataset for the fields available for 'full-list-fields'
      parameters:
        - $ref: '#/parameters/fulllistParam'
        - $ref: '#/parameters/fulllistfieldsParam'
      responses:
        '200':
          description: list of datasets
          schema:
            type: array
            items:
              allOf:
                - $ref: '#/definitions/dataset'
                - $ref: '#/definitions/uuid'
    post:
      tags:
        - 'datasets'
      summary: Imports a dataset form a imgapi compatible server
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              url:
                description: url of the manifest to import
                type: string
      responses:
        '303':
          description: Redirect to new org
  '/{uuid}':
    get:
      tags:
        - 'datasets'
      summary: Reads a Dataset
      parameters:
        - name: uuid
          in: path
          description: UUID of the datasets
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/dataset'
    delete:
      tags:
        - 'datasets'
      summary: Reads a Dataset
      parameters:
        - name: uuid
          in: path
          description: UUID of the datasets
          required: true
          type: string
      responses:
        '200':
          description: OK
    put:
      tags:
        - 'datasets'
      summary: Upload a manifest
      description: |
        This is the 1st step of a dataset import from a local file
      parameters:
        - name: uuid
          in: path
          description: UUID of the dataset to import
          required: true
          type: string
      responses:
        '303':
          description: Redirect to new org
  '/{uuid}/dataset.gz':
    get:
      tags:
        - 'datasets'
      summary: Downloads a zVol
      parameters:
        - name: uuid
          in: path
          description: UUID of the datasets
          required: true
          type: string
      responses:
        '200':
          description: OK
    put:
      tags:
        - 'datasets'
      summary: Uploads a zvol
      description: |
        This is the 2nd step of a dataset import from a local file
      parameters:
        - name: uuid
          in: path
          description: UUID of the dataset to import
          required: true
          type: string
      responses:
        '303':
          description: Redirect to new org
  '/{uuid}/networks/{nic}':
    put:
      tags:
        - 'datasets'
      summary: Adds or modifies a nic on the dataset
      parameters:
        - name: uuid
          in: path
          description: UUID of the dataset to import
          required: true
          type: string
        - name: nic
          in: path
          description: name of the nic to add (i.e. 'net1')
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              description:
                description: description of the interface
                type: string
      responses:
        '200':
          description: OK
    delete:
      tags:
        - 'datasets'
      summary: Adds or modifies a nic on the dataset
      parameters:
        - name: uuid
          in: path
          description: UUID of the dataset to import
          required: true
          type: string
        - name: nic
          in: path
          description: name of the nic to add (i.e. 'net1')
          required: true
          type: string
      responses:
        '200':
          description: OK