swagger: '2.0'
basePath: /api/3/hypervisors
consumes:
  - applicaiton/json
produces:
  - applicaiton/json
info:
  version: 3.0.0
  title: Hypervisors
parameters:
  fulllistParam:
    name: full-list
    in: query
    description: Enables or disables the return ov objects rather then uuids
    required: false
    allowEmptyValue: false
    type: boolean
    format: boolean
  fulllistfieldsParam:
    name: full-list-fields
    in: query
    description: Fields to be returnd when full-list is enabled
    required: false
    format: string
    type: array
    items:
      type: string
    collectionFormat: csv
definitions:
  uuid:
    type: string
    pattern: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
  metrics:
    type: object
    properties:
      '<key>':
        type: array
        items:
          type: integer
  hypervisor:
    properties:
      alias:
        type: string
      metadata:
        type: object
      characteristics:
        type: object
      etherstubs:
        type: object
      host:
        type: string
      networks:
        type: array
        items:
          type: string
      path:
        type: array
        items:
          type: string
      pools:
        type: object
      port:
        type: integer
      resources:
        type: object
      services:
        type: object
      sysinfo:
        type: object
      version:
        type: string
      virtualisation:
        type: array
        items:
          type: string
      uuid:
        $ref: '#/definitions/uuid'
paths:
  #------------------
  # Hypervisors
  #------------------
  '/':
    get:
      tags:
        - 'hypervisors'
      summary: lists all hypervisors visible to the user
      description: |
        See 'get hypervisor' for the fields available for 'full-list-fields'
      parameters:
        - $ref: '#/parameters/fulllistParam'
        - $ref: '#/parameters/fulllistfieldsParam'
      responses:
        '200':
          description: list of hypervisors
          schema:
            type: array
            items:
              allOf:
                - $ref: '#/definitions/hypervisor'
                - $ref: '#/definitions/uuid'
  '/{uuid}':
    get:
      tags:
        - 'hypervisors'
      summary: reads a hypervisor
      parameters:
        - name: uuid
          in: path
          description: uuid of the hypervisor
          required: true
          type: string
      responses:
        '200':
          description: returns an hypervisor
          schema:
            $ref: '#/definitions/hypervisor'
    delete:
      tags:
        - 'hypervisors'
      summary: deletes a hypervisor.
      description: |
        Every vm still residing on this hypervisor
        will either be put in 'limbo' when at least one full backup exists,
        or be deleted if not.
      parameters:
        - name: uuid
          in: path
          description: uuid of the hypervisor
          required: true
          type: string
      responses:
        '200':
          description: ok
  '/{uuid}/characteristics/{path}':
    put:
      tags:
        - 'hypervisors'
      summary: Sets a hypervisor characteristic.
      description: |
        this can be later used on rules to match against.
      parameters:
        - name: uuid
          in: path
          description: uuid of the hypervisor
          required: true
          type: string
        - name: path
          in: path
          description: url path prefix of the characteristic
          required: true
          type: string
      responses:
        '200':
          description: ok
    delete:
      tags:
        - 'hypervisors'
      summary: removes a characteristic from a hypervisor
      parameters:
        - name: uuid
          in: path
          description: uuid of the hypervisor
          required: true
          type: string
        - name: path
          in: path
          description: url path to characteristic to delete
          required: true
          type: string
      responses:
        '200':
          description: ok
  '/{uuid}/config':
    put:
      tags:
        - 'hypervisors'
      summary: sets a configuration / alias of the hypervisor
      parameters:
        - name: uuid
          in: path
          description: uuid of the hypervisor
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              alias:
                description: new alias of the hypervisor
                type: string
      responses:
        '200':
          description: ok
  '/{uuid}/metrics':
    get:
      tags:
        - 'hypervisors'
      summary: Reads a VM
      parameters:
        - name: uuid
          in: path
          description: uuid of the hypervisor
          required: true
          type: string
      responses:
        '200':
          description: returns metrics for the hypervisor
          schema:
            $ref: '#/definitions/metrics'
        '503':
          description: No metric server.