swagger: '2.0'
basePath: /api/3/networks
consumes:
  - applicaiton/json
produces:
  - applicaiton/json
info:
  version: 3.0.0
  title: Networks
parameters:
  fulllistParam:
    name: full-list
    in: query
    description: Enables or disables the return ov objects rather then uuids
    required: false
    allowEmptyValue: false
    type: boolean
    format: boolean
  fulllistfieldsParam:
    name: full-list-fields
    in: query
    description: Fields to be returnd when full-list is enabled
    required: false
    format: string
    type: array
    items:
      type: string
    collectionFormat: csv
definitions:
  uuid:
    type: string
    pattern: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
  network:
    properties:
      metadata:
        type: object
      name:
        type: string
      ipranges:
        type: array
        items:
          $ref: '#/definitions/uuid'
      uuid:
        $ref: '#/definitions/uuid'
paths:  
  #------------------
  # Networks
  #------------------
  '/':
    get:
      summary: Lists all networks visible to the user.
      description: |
        See 'Get Network' for the fields available for 'full-list-fields'
      parameters:
        - $ref: '#/parameters/fulllistParam'
        - $ref: '#/parameters/fulllistfieldsParam'
      responses:
        '200':
          description: list of networks
          schema:
            type: array
            items:
              allOf:
                - $ref: '#/definitions/network'
                - $ref: '#/definitions/uuid'
    post:
      summary: Creates a new network
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              name:
                description: name of the network
                type: string
      responses:
        '303':
          description: Redirect to new org
  '/{uuid}':
    get:
      summary: reads a network
      parameters:
        - name: uuid
          in: path
          description: uuid of the network
          required: true
          type: string
      responses:
        '200':
          description: list of networks
          schema:
            $ref: '#/definitions/uuid'
    delete:
      summary: deletes a network
      parameters:
        - name: uuid
          in: path
          description: uuid of the network
          required: true
          type: string
      responses:
        '200':
          description: OK
  '/{uuid}/iprange/{iprange}':
    put:
      summary: Adds an iprange to a network
      parameters:
        - name: uuid
          in: path
          description: uuid of the user to delete
          required: true
          type: string
        - name: iprange
          in: path
          description: uuid of the iprange to add
          required: true
          type: string
      responses:
        '200':
          description: OK
    delete:
      summary: Removes an IP Range from an network
      parameters:
        - name: uuid
          in: path
          description: uuid of the user to delete
          required: true
          type: string
        - name: iprange
          in: path
          description: uuid of the iprange to add
          required: true
          type: string
      responses:
        '200':
          description: OK