swagger: '2.0'
basePath: /api/3/oauth2
consumes:
  - application/json
produces:
  - application/json
info:
  version: 3.0.0
  title: OAuth2
###################
# Path definitions
###################
paths:
  #------------------
  # OAuth2
  #------------------
  '/auth':
    get:
      summary: OAuth2 Authorization Code Request and Implict Request
      description: |
        This endpoint serves both 'Authorization Code Request' and the
        'Implict Request' parts of the OAuth 2 workflow depending on the
        *response_type* provided.
      parameters:
        - name: response_type
          in: query
          type: string
          required: true
          enum:
            - 'code'
            - 'token'
        - name: client_id
          in: query
          type: string
          required: true
          description: ID of the client
        - name: redirect_uri
          in: query
          type: string
          description: The URI redirected to at the end of the OAuth2 dance
          required: true
        - name: state
          in: query
          type: string
          description: client state that gets passed back to the redirect uri
        - name: scope
          in: query
          type: string
          description: list of scopes to claim
      responses:
        200:
          description: Redirect to new user
    post:
      summary: Authorization Code grant and 
      description: |
        Serves both the Authorization Code Grant and Implict Grant
        * [4.1.1 Authorization Code Grant / Authorization Request](https://tools.ietf.org/html/rfc6749#section-4.1.1)
        * [4.2.1 Implicit Grant / Authorization Request](https://tools.ietf.org/html/rfc6749#section-4.2.1)
      consumes:
        - 'application/x-www-form-urlencoded'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              response_type:
                type: string
                enum:
                  - 'code'
                  - 'token'
              client_id:
                type: string
                description: ID of the client
              redirect_uri:
                type: string
                description: The URI redirected to at the end of the OAuth2 dance
              scope:
                type: array
                items:
                  type: string
                description: list of scopes to claim
              state:
                type: string
                description: client state that gets passed back to the redirect uri
              username:
                type: string
                description: the username
              password:
                type: string
                description: the password
      responses:
        302:
          description: |
            Redirects to the redirect_uri with the `access_code` as query
            parameter.
  '/token':
    post:
      summary: OAuth2 token endpoint
      description: |
        This endpoint serves the following parts of the OAuth workflow, please
        see the linked specifications for details as it does not fit the swagger
        spec definition language.
        * [4.1.3 Access Token Request](https://tools.ietf.org/html/rfc6749#section-4.1.3)
        * [4.4.2 Access Token Request](https://tools.ietf.org/html/rfc6749#section-4.4.2)
        * [4.2.1 Implicit Grant / Authorization Request](https://tools.ietf.org/html/rfc6749#section-4.2.1)
        * [4.3 Resource Owner Password Credentials Grant](https://tools.ietf.org/html/rfc6749#section-4.3)
        * [6 Refreshing an Access Token](https://tools.ietf.org/html/rfc6749#section-6)
      consumes:
        - 'application/x-www-form-urlencoded'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              grant_type:
                type: string
                enum:
                  - authorization_code
                  - client_credentials
                  - refresh_token
                  - password
      responses:
        200:
          description: The token was sucessfully provided.
          schema:
            type: object
            properties:
              access_token:
                type: string
              token_type:
                type: string
                enum:
                  - 'bearer'
              expires_in:
                type: integer
              refresh_token:
                type: string
                description: Only for Access Token Request
              scope:
                type: array
                items:
                  type: string