swagger: '2.0'
basePath: /api/3/roles
consumes:
  - applicaiton/json
produces:
  - applicaiton/json
info:
  version: 3.0.0
  title: Roles
parameters:
  fulllistParam:
    name: full-list
    in: query
    description: Enables or disables the return ov objects rather then uuids
    required: false
    allowEmptyValue: false
    type: boolean
    format: boolean
  fulllistfieldsParam:
    name: full-list-fields
    in: query
    description: Fields to be returnd when full-list is enabled
    required: false
    format: string
    type: array
    items:
      type: string
    collectionFormat: csv
definitions:
  uuid:
    type: string
    pattern: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
  permission:
    type: array
    items:
      type: string
  role:
    properties:
      metadata:
        type: object
      name:
        type: string
      permissions: 
        type: array
        items:
          $ref: '#/definitions/permission'
      uuid:
        $ref: '#/definitions/uuid'
paths:
  #------------------
  # Roles
  #------------------
  '/':
    get:
      summary: Lists all roles visible to the user
      description: |
        See Get Roles for the fields available for 'full-list-fields'
      parameters:
        - $ref: '#/parameters/fulllistParam'
        - $ref: '#/parameters/fulllistfieldsParam'
      responses:
        '200':
          description: list of roles
          schema:
            type: array
            items:
              allOf:
                - $ref: '#/definitions/role'
                - $ref: '#/definitions/uuid'
    post:
      summary: Creates a new role
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              name:
                description: Name of the role
                type: string
              secret:
                description: the secret for the client
                type: array
                items:
                  type: string
      responses:
        '303':
          description: Redirect to new client
  '/{uuid}':
    get:
      summary: Reads a role
      parameters:
        - name: uuid
          in: path
          description: UUID of the role
          required: true
          type: string
      responses:
        '200':
          description: returns a role
          schema:
            $ref: '#/definitions/role'
    delete:
      summary: Deletes a role
      parameters:
        - name: uuid
          in: path
          description: UUID of the role
          required: true
          type: string
      responses:
        '200':
          description: OK
  '/{uuid}/permissions/{permission}':
    put:
      summary: Grants a permission to a role.
      parameters:
        - name: uuid
          in: path
          description: UUID of the role
          required: true
          type: string
        - name: permission
          in: path
          description: |
            the permission to grant as path i.e. 'some/funky/permission'
          required: true
          type: string
      responses:
        '200':
          description: OK
    delete:
      summary: Revokes a permission from a role
      parameters:
        - name: uuid
          in: path
          description: UUID of the role
          required: true
          type: string
        - name: permission
          in: path
          description: |
            the permission to revoke as path i.e. 'some/funky/permission'
          required: true
          type: string
      responses:
        '200':
          description: OK