swagger: '2.0'
basePath: /api/3/scopes
consumes:
  - application/json
produces:
  - application/json
info:
  version: 3.0.0
  title: Scopes
###################
# Path definitions
###################
paths:
  #------------------
  # Scope
  #------------------
  '/':
    get:
      summary: lists the scopes
      responses:
        200:
          description: The list of the
          schema:
            type: array
            items:
              type: object
              properties:
                'default':
                  type: boolean
                  description: weather this scope is a default scope or not
                'description':
                  type: string
                  description: the description of the scope
                'scope':
                  type: string
                  description: "the name of the scope"